return {
	{
		"nvim-treesitter/nvim-treesitter",
		opts = {
			ensure_installed = {
				"javascript",
				"typescript",
				"css",
				"gitignore",
				"graphql",
				"http",
				"json",
				"scss",
				"sql",
				"vim",
				"lua",
				"xml",
				"python",
 			  "rust",
  			"go",
  			"php",
  			"java",
  			"yaml",
  			"dockerfile",
  			"markdown",
  			"markdown_inline",
  			"bash",
			},
			query_linter = {
				enable = false,
				use_virtual_text = true,
				lint_events = { "BufWrite", "CursorHold" },
			},
		},
	},
}
